version: '3.8'

services:
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=stori
      - POSTGRES_PASSWORD=storichallenge
      - POSTGRES_DB=stori
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  function:
    build: ./transactions_summary
    volumes:
      - ./email_responses:/email_responses
      - ./zip:/zip
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://stori:stori@db/stori
      - FROM_EMAIL=llanes.ariel.enrique@gmail.com
      - TO_EMAIL=
