CREATE EXTENSION citext;
CREATE TABLE IF NOT EXISTS accounts
(
    "account_id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "creation_date" timestamp without time zone NOT NULL,
    "username" varchar NOT NULL,
    "email" citext UNIQUE
);
CREATE TABLE IF NOT EXISTS transactions
(
    "transaction_id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "account_id" int,
    "date" timestamp without time zone NOT NULL,
    "value" real NOT NULL,
    CONSTRAINT fk_account
        FOREIGN KEY(account_id)
            REFERENCES accounts(account_id)
);