ARG FUNCTION_DIR="/function"
ARG CSV_DIR="/transactions_files"

FROM python:3.11 as build-image

ARG FUNCTION_DIR CSV_DIR

RUN mkdir -p ${FUNCTION_DIR}
RUN mkdir -p ${CSV_DIR}

COPY ./ ${FUNCTION_DIR}
COPY transactions_files/example.csv ${CSV_DIR}

RUN pip install --no-cache-dir --target ${FUNCTION_DIR}/pip_libs  -r ${FUNCTION_DIR}/requirements.txt

# Use a slim version of the base Python image to reduce the final image size
FROM python:3.11-slim

# Include global arg in this stage of the build
ARG FUNCTION_DIR
ARG CSV_DIR

# ADD envs
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH "${PYTHONPATH}:${FUNCTION_DIR}/pip_libs"

# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}

# Copy in the built dependencies
COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}
COPY --from=build-image ${CSV_DIR} ${CSV_DIR}

CMD ["python", "txns.py"]