ARG FUNCTION_DIR="/function"
ARG CSV_DIR="/transactions_files"

FROM python:3.10 as build-image

ENV PIP_ROOT_USER_ACTION=ignore

ARG FUNCTION_DIR CSV_DIR

RUN mkdir -p ${FUNCTION_DIR}
RUN mkdir -p ${CSV_DIR}

COPY ./ ${FUNCTION_DIR}
COPY transactions_files/example.csv ${CSV_DIR}

RUN pip install --upgrade pip
RUN pip install \
    --platform manylinux2014_x86_64 \
    --implementation cp \
    --python-version 3.10 \
    --only-binary=:all: --upgrade\
    --no-cache-dir \
    --target ${FUNCTION_DIR}/pip_packages \
    -r ${FUNCTION_DIR}/requirements.txt

# Use a slim version of the base Python image to reduce the final image size
FROM python:3.10-slim

# Include global arg in this stage of the build
ARG FUNCTION_DIR
ARG CSV_DIR

# Install Make
RUN apt update
RUN apt -y --no-install-recommends install make zip

# ADD envs
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH "${PYTHONPATH}:${FUNCTION_DIR}/pip_packages"

# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}

# Copy in the built dependencies
COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}
#ADD Makefile ${FUNCTION_DIR}
COPY --from=build-image ${CSV_DIR} ${CSV_DIR}

CMD ["python", "txns.py"]